name: release

on:
  push:
    branches:
      - main

jobs:
  publish-npm-registry:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Set Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: yarn install --immutable --inline-builds --immutable-cache --check-cache
      - run: yarn build:all
      - run: yarn test:all

      - name: Create .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "@danbileee:registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

      - name: Deploy
        run: |
          var=`npx lerna version --conventional-commits --yes && npx lerna publish from-git --yes`
          echo $var > foo.txt
          val=$( cat foo.txt )
          echo "DEPLOY_RESULT=$val" >> $GITHUB_ENV
            
      - name: Delete .npmrc
        if: always()
        run: |
          rm .npmrc

      - run: echo "$DEPLOY_RESULT"
